spring:
  profiles:
    active: -dev
---
server:
  port: 8001
spring:
  application:
    name: MICRO-SERVER-DEV
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8002
spring:
  application:
    name: MICRO-SERVER-TEST
  profiles: test #开发环境
eureka:
  client:
    service-url:
defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8003
spring:
  application:
    name: MICRO-SERVER-BAND
  profiles: band #开发环境
eureka:
  client:
    service-url:
defaultZone: http://localhost:7001/eureka/